#!/bin/bash
cd "$(dirname "${0}")"

ACTIVATE='venv/bin/activate'
[ -f "${ACTIVATE}" ] && USE_VENV=true || USE_VENV=false

$USE_VENV && source "${ACTIVATE}"
python3 -m evowluator.main "$@"
$USE_VENV && deactivate
